export const LOAD_TOP_JOBS_BEGIN = 'LOAD_TOP_JOBS_BEGIN';
export const LOAD_TOP_JOBS_SUCCESS = 'LOAD_TOP_JOBS_SUCCESS';
export const LOAD_TOP_JOBS_FAIL = 'LOAD_TOP_JOBS_FAIL';

export const LOAD_JOB_BEGIN = 'LOAD_JOB_BEGIN';
export const LOAD_JOB_SUCCESS = 'LOAD_JOB_SUCCESS';
export const LOAD_JOB_FAIL = 'LOAD_JOB_FAIL';

export const INCREMENT_JOB_OFFSET = 'INCREMENT_JOB_OFFSET';
