export const LOAD_TOP_STORIES_BEGIN = 'LOAD_TOP_STORIES_BEGIN';
export const LOAD_TOP_STORIES_SUCCESS = 'LOAD_TOP_STORIES_SUCCESS';
export const LOAD_TOP_STORIES_FAIL = 'LOAD_TOP_STORIES_FAIL';

export const LOAD_TOP_JOBS_BEGIN = 'LOAD_TOP_JOBS_BEGIN';
export const LOAD_TOP_JOBS_SUCCESS = 'LOAD_TOP_JOBS_SUCCESS';
export const LOAD_TOP_JOBS_FAIL = 'LOAD_TOP_JOBS_FAIL';
