export const LOAD_NEW_STORIES_BEGIN = 'LOAD_NEW_STORIES_BEGIN';
export const LOAD_NEW_STORIES_SUCCESS = 'LOAD_NEW_STORIES_SUCCESS';
export const LOAD_NEW_STORIES_FAIL = 'LOAD_NEW_STORIES_FAIL';

export const LOAD_STORY_BEGIN = 'LOAD_STORY_BEGIN';
export const LOAD_STORY_SUCCESS = 'LOAD_STORY_SUCCESS';
export const LOAD_STORY_FAIL = 'LOAD_STORY_FAIL';

export const INCREMENT_NEW_STORY_OFFSET = 'INCREMENT_OFFSET';